config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items
  # get 'home/index'
  get 'home/about'
  # root 'home#index'
  root 'items#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    # @item = Item.new
    @item = current_user.items.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    # @item = Item.new(item_params)
    @item = current_user.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_url, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @item = current_user.items.find_by(id: params[:id])
    redirect_to items_path, notice: "Not Authorized To Edit This Item!" if @item.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:product, :product_link, :bought_price, :current_value, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
  <div class="container-fluid px-5">
    <%= link_to 'Profit Tracker', root_path, class:"navbar-brand text-primary" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Products', items_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us:</h1>
<p>To be added...</p>

app/views/home/index.html.erb
<h1>Home</h1>
<p>A Profit Tracker for Your Inventory.</p>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= form.label :product, style: "display: block", class: "form-label"%>
    <%= form.text_field :product, class: "form-control", required: true %>
  </div>
  <div class="field form-group">
    <%= form.label :product_link, "Product Link (Optional)", class: "form-label" %>
    <%= form.text_field :product_link, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :bought_price, style: "display: block", class: "form-label" %>
    <%= form.number_field :bought_price, class: "form-control", required: true %>
  </div>
  <div class="field form-group">
    <%= form.label :current_value, style: "display: block", class: "form-label" %>
    <%= form.number_field :current_value, class: "form-control", required: true %>
  </div>
  <div class="field form-group">
    <%= form.number_field :user_id, id: :item_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>
  <div>
    <%= form.submit "Add Product", class: "btn btn-primary my-4" %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>Product:</strong>
    <%= item.product %>
  </p>

  <p>
    <strong>Product link:</strong>
    <%= item.product_link %>
  </p>

  <p>
    <strong>Bought price:</strong>
    <%= item.bought_price %>
  </p>

  <p>
    <strong>Current value:</strong>
    <%= item.current_value %>
  </p>

</div>

app/views/items/edit.html.erb
<div class="d-flex justify-content-between my-3">
  <h1>Editing Product</h1>
  <div>
    <%= link_to "Show this item", @item, class: "btn btn-primary my-auto me-2" %>
    <%= link_to "Back to items", items_path, class: "btn btn-warning my-auto" %>
  </div>
</div>
<%= render "form", item: @item %>
<br>

app/views/items/index.html.erb
<% if user_signed_in? %>
  <div class="d-flex justify-content-between my-3">
    <h1>Product List</h1>
    <%= link_to "Add New Product", new_item_path, class:"btn btn-success my-auto"%>
  </div>
  <div id="items">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Product Name</th>
          <th>Product Link</th>
          <th>Purchased Price</th>
          <th>Current Value</th>
          <th>Profit</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <% if item.user == current_user %>
            <tr class="<%= item.current_value - item.bought_price > 0 ? 'table-success' : (item.current_value - item.bought_price < 0 ? 'table-danger' : 'table-secondary') %>">
              <td><%= link_to item.product, item %></td>
              <td>
                <% unless item.product_link.nil? || item.product_link.empty? %>
                  <a href="<%= item.product_link %>" target="_blank">Link to Product</a>
                <% else %>
                  <%= item.product_link %>
                <% end %>
              </td>
              <td><%= item.bought_price %></td>
              <td><%= item.current_value %></td>
              <td><%= (item.current_value - item.bought_price) %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="2">Total</td>
          <td><%= @items.select { |item| item.user == current_user }.sum(&:bought_price) %></td>
          <td><%= @items.select { |item| item.user == current_user }.sum(&:current_value) %></td>
          <td><%= @items.select { |item| item.user == current_user }.sum { |item| item.current_value - item.bought_price } %></td>
        </tr>
      </tfoot>
    </table>
  </div>
<% else %>
  <h1>Home</h1>
  <p>A Profit Tracker for Your Inventory.</p>
  <%# <%= link_to 'Sign In', new_user_session_path, class: "btn btn-primary my-4" %>
  <%# <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-primary my-4" %>
<% end %>

app/views/items/new.html.erb
<div class="d-flex justify-content-between my-3">
  <h1>New product</h1>
  <%= link_to "Back to items", items_path, class: "btn btn-warning my-auto" %>
</div>
<%= render "form", item: @item %>
<br>

app/views/items/show.html.erb
<div class="d-flex justify-content-end my-3">
  <%= link_to "Back to items", items_path, class: "btn btn-warning my-auto" %>
</div>
<%= render @item %>
<div class="d-flex">
  <%= link_to "Edit this item", edit_item_path(@item), class: "btn btn-primary my-auto me-2" %>
  <%= button_to "Destroy this item", @item, method: :delete, class: "btn btn-danger my-2" %>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <title>Profit Tracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'home/header' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>